title: Vishal Gaikwad
logo: /assets/img/Vishal_Photo.jpg
description: I'm working on Data science and Machine larning related problems.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
